"""add_content_field_to_article

Revision ID: 9df5c6353542
Revises: ed3b3babc76b
Create Date: 2025-11-06 09:00:40.719293

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "9df5c6353542"
down_revision: Union[str, Sequence[str], None] = "ed3b3babc76b"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("articles", sa.Column("content", sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("articles", "content")
    # ### end Alembic commands ###
