"""add retrieval pipeline tables and indexes

Revision ID: a929819b432a
Revises: 9df5c6353542
Create Date: 2025-11-08 04:08:27.107352

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a929819b432a"
down_revision: Union[str, Sequence[str], None] = "9df5c6353542"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "verification_requests",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("original_text", sa.Text(), nullable=False),
        sa.Column("text_hash", sa.String(length=64), nullable=False),
        sa.Column("clean_query", sa.Text(), nullable=True),
        sa.Column("claims", postgresql.JSON(astext_type=sa.Text()), nullable=True),
        sa.Column(
            "status",
            sa.Enum(
                "PENDING",
                "PROCESSING",
                "COMPLETED",
                "FAILED",
                name="verificationstatus",
            ),
            nullable=False,
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_verification_requests_text_hash"),
        "verification_requests",
        ["text_hash"],
        unique=True,
    )
    op.create_table(
        "retrieval_results",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("request_id", sa.UUID(), nullable=False),
        sa.Column(
            "retrieved_chunks_json",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Top chunks from RRF fusion with scores",
        ),
        sa.Column(
            "reranked_chunks_json",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Top-N chunks after OpenAI reranking",
        ),
        sa.Column(
            "final_articles_json",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Aggregated article results with scores",
        ),
        sa.Column(
            "processing_time_ms",
            sa.Integer(),
            nullable=True,
            comment="Total pipeline processing time in milliseconds",
        ),
        sa.Column(
            "stage_timings_json",
            postgresql.JSON(astext_type=sa.Text()),
            nullable=True,
            comment="Breakdown of time spent in each pipeline stage",
        ),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["request_id"], ["verification_requests.id"], ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    op.add_column(
        "article_chunks",
        sa.Column(
            "search_vector",
            postgresql.TSVECTOR(),
            nullable=True,
            comment="Vietnamese-aware tsvector for BM25 search",
        ),
    )
    op.add_column(
        "article_chunks",
        sa.Column(
            "article_title",
            sa.String(length=512),
            nullable=True,
            comment="Denormalized from Article",
        ),
    )
    op.add_column(
        "article_chunks",
        sa.Column(
            "source_name",
            sa.String(length=256),
            nullable=True,
            comment="Denormalized from NewsSource",
        ),
    )
    op.add_column(
        "article_chunks",
        sa.Column(
            "published_at",
            sa.DateTime(timezone=True),
            nullable=True,
            comment="Denormalized from Article",
        ),
    )

    # Add GIN index for full-text search on search_vector
    op.create_index(
        "ix_article_chunks_search_vector",
        "article_chunks",
        ["search_vector"],
        postgresql_using="gin",
    )

    # Add IVFFlat index for vector similarity search (100 lists for ~10k-100k vectors)
    # Using cosine distance operator (<=>)
    op.execute(
        "CREATE INDEX ix_article_chunks_embedding_ivfflat "
        "ON article_chunks "
        "USING ivfflat (embedding vector_cosine_ops) "
        "WITH (lists = 100);"
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    # Drop indexes first
    op.execute("DROP INDEX IF EXISTS ix_article_chunks_embedding_ivfflat;")
    op.drop_index("ix_article_chunks_search_vector", table_name="article_chunks")

    op.drop_column("article_chunks", "published_at")
    op.drop_column("article_chunks", "source_name")
    op.drop_column("article_chunks", "article_title")
    op.drop_column("article_chunks", "search_vector")
    op.drop_table("retrieval_results")
    op.drop_index(
        op.f("ix_verification_requests_text_hash"), table_name="verification_requests"
    )
    op.drop_table("verification_requests")

    # Drop the ENUM type
    op.execute("DROP TYPE IF EXISTS verificationstatus;")
    # ### end Alembic commands ###
